CREATE TABLE TB_PEDIDO (
    ID_PEDIDO SERIAL PRIMARY KEY,
    UUID UUID DEFAULT gen_random_uuid(),
    ID_VENTA INT NOT NULL UNIQUE,
	ID_SUCURSAL INT,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DIRECCION_ENTREGA VARCHAR(255) NOT NULL,
    LATITUD NUMERIC(10,6) NOT NULL,
    LONGITUD NUMERIC(10,6) NOT NULL,
    NUMERO_PEDIDO VARCHAR(50) NOT NULL UNIQUE,
    QR_VERIFICATION_CODE VARCHAR(150) NOT NULL UNIQUE,
    ID_REPARTIDOR INT,
    MOVILIDAD CHAR(1) NOT NULL,
    FECHA_ASIGNACION TIMESTAMP,            -- momento en el q se setea el estado a AS
    FECHA_EN_CAMINO TIMESTAMP,             -- momento en el q se setea el estado a EC
    FECHA_ENTREGA TIMESTAMP,               -- momento en el q se setea el estado a EN
    TIEMPO_ENTREGA_MINUTOS SMALLINT,       -- métrica de negocio (dif d minutos entre EN y EC)
    ESTADO VARCHAR(2) DEFAULT 'PE',
    OBSERVACIONES TEXT,

    CONSTRAINT CHK_ESTADO_PEDIDO CHECK (ESTADO IN ('PE','AS','EC','CR','EN','FA')),
    CONSTRAINT CHK_MOVILIDAD CHECK (MOVILIDAD IN ('M', 'C'))
	--leyenda de estados
	--PE -> PENDIENTE
	--AS -> ASIGNADO(aceptado) 
	--EC -> EN CAMINO
	--CR -> CERCA
	--EN -> ENTREGADO
	--FA -> FALLIDO
);
