CREATE TABLE TB_ROL (
    ID_ROL SERIAL PRIMARY KEY,
    DESCRIPCION CHAR(20) NOT NULL
);

CREATE TABLE TB_CARGO(
	ID_CARGO SERIAL PRIMARY KEY,
	DESCRIPCION CHAR(20) NOT NULL 
);

CREATE TABLE TB_DISTRITO (
    ID_DISTRITO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE TB_USUARIO (
    ID_USUARIO SERIAL PRIMARY KEY,
	UUID UUID DEFAULT gen_random_uuid(),
    NOMBRES VARCHAR(50) NOT NULL,
    APE_MATERNO VARCHAR(50) NOT NULL,
    APE_PATERNO VARCHAR(50) NOT NULL,
    CORREO VARCHAR(50) UNIQUE NOT NULL,
    CLAVE VARCHAR(100) NOT NULL,
	TIPO_DOC CHAR(3) NOT NULL 
	CHECK(TIPO_DOC IN('DNI','PAS','CDX','CMP')),
	--DNI, PASAPORTE, CARNET DE EXTRANJERIA, CARNET MILITAR/POLICIAL
    NRO_DOC VARCHAR(15) UNIQUE NOT NULL,
    DIRECCION VARCHAR(70),
    ID_DISTRITO INT NOT NULL,
    TELEFONO CHAR(9) NOT NULL,
    ID_ROL INT DEFAULT 2,
	ID_CARGO INT,
	ID_EMPRESA INT,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	IMAGEN VARCHAR(150) DEFAULT NULL,
	PUBLIC_ID VARCHAR(100) DEFAULT NULL,
    ESTADO BOOLEAN DEFAULT TRUE,
    FCM_TOKEN VARCHAR(500) NULL,
    FCM_TOKEN_FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_DISTRITO) REFERENCES TB_DISTRITO(ID_DISTRITO),
    FOREIGN KEY (ID_ROL) REFERENCES TB_ROL(ID_ROL),
	FOREIGN KEY (ID_CARGO) REFERENCES TB_CARGO(ID_CARGO)
);