CREATE TABLE TB_VENTA (
    ID_VENTA SERIAL PRIMARY KEY,
	UUID UUID DEFAULT gen_random_uuid(),
	IDEMPOTENCIA_KEY VARCHAR(100) UNIQUE,
    ID_USUARIO INT,
	ID_SUCURSAL INT,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TOTAL NUMERIC(11,2),
    ESTADO CHAR(1) DEFAULT 'G', -- G,P,E,C
    TIPO_VENTA CHAR(1) DEFAULT 'R', -- R, P
    METODO_ENTREGA CHAR(1), -- S, D
	ESPECIFICACIONES TEXT,
    CONSTRAINT EST_CHECK CHECK (ESTADO IN ('G','P','E','C')),
    CONSTRAINT TIPO_VENTA_CHECK CHECK (TIPO_VENTA IN ('P','R')),
    CONSTRAINT MET_ENTREGA_CHECK CHECK (METODO_ENTREGA IN ('D','S') OR METODO_ENTREGA IS NULL)
);

CREATE TABLE TB_DETALLE_VENTA (
    ID_DETALLE_VENTA SERIAL PRIMARY KEY,
    ID_VENTA INT NOT NULL,
    ID_PRODUCTO_SUCURSAL INT NOT NULL,
    CANTIDAD SMALLINT NOT NULL,
	PRECIO_UNITARIO NUMERIC(10,2), --ESTE PRECIO SERA PARA GUARDAR LOS PRECIOS QUE SE COMPRARON EN ESE MOMENTO
    SUB_TOTAL NUMERIC(10,2) NOT NULL,
    FOREIGN KEY (ID_VENTA) REFERENCES TB_VENTA(ID_VENTA)
);
