CREATE TABLE TB_EMPRESA(
	ID_EMPRESA SERIAL PRIMARY KEY,
    RUC CHAR(11) NOT NULL UNIQUE,
    RAZON_SOCIAL VARCHAR(100) NOT NULL,
	IMAGEN VARCHAR(150) DEFAULT NULL,
	PUBLIC_ID VARCHAR(100) DEFAULT NULL,
    TELEFONO CHAR(15) NOT NULL,
    DIRECCION VARCHAR(80) NOT NULL,
    ID_DISTRITO INT NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO BOOLEAN DEFAULT TRUE
);

CREATE TABLE TB_SUCURSAL(
    ID_SUCURSAL SERIAL PRIMARY KEY,
	NOMBRE_UBICACION VARCHAR(50) NOT NULL, --PRIMAVERA/DASO/MIRAFLORES/ETC
	ID_EMPRESA INT,
	IMAGEN VARCHAR(150),
	PUBLIC_ID VARCHAR(100) DEFAULT NULL,
	ID_DISTRITO INT,
	DIRECCION VARCHAR(80) NOT NULL,
	FECHA_APERTURA DATE,

	FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA)
);


CREATE TABLE TB_PRODUCTO_SUCURSAL(
	ID_PRODUCTO_SUCURSAL SERIAL PRIMARY KEY,
	ID_PRODUCTO INT,
	ID_SUCURSAL INT,
	MIN_STOCK INT,
	STOCK INT DEFAULT 1,
	MAX_STOCK INT,
	PRECIO NUMERIC(10,2) NOT NULL,
	ESTADO BOOLEAN DEFAULT TRUE,

    FOREIGN KEY (ID_SUCURSAL) REFERENCES TB_SUCURSAL(ID_SUCURSAL),
	UNIQUE (ID_PRODUCTO, ID_SUCURSAL)
);
