CREATE TABLE TB_CATEGORIA (
    ID_CATEGORIA SERIAL PRIMARY KEY,
    DESCRIPCION VARCHAR(100) NOT NULL,
	IMAGEN varchar(150) DEFAULT NULL,
	PUBLIC_ID VARCHAR(100)DEFAULT NULL
);

CREATE TABLE TB_SUBCATEGORIA(
	ID_SUBCATEGORIA SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
    ID_CATEGORIA INT,
	
    FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE TB_PRODUCTO (
    ID_PRODUCTO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    ID_EMPRESA INT, -- A QUE TIENDA LE PERTENECE CADA PRODUCTO
    ID_SUBCATEGORIA INT,
    IMAGEN VARCHAR(150) DEFAULT NULL, 
	PUBLIC_ID VARCHAR(100) DEFAULT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO BOOLEAN DEFAULT TRUE,
	
    FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES TB_SUBCATEGORIA(ID_SUBCATEGORIA)
);
