CREATE TABLE TB_DISTRITO (
    ID_DISTRITO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE TB_CATEGORIA (
    ID_CATEGORIA SERIAL PRIMARY KEY,
    DESCRIPCION VARCHAR(100) NOT NULL,
	IMAGEN varchar(150) DEFAULT NULL,
	PUBLIC_ID VARCHAR(100)DEFAULT NULL
);

CREATE TABLE TB_SUBCATEGORIA(
	ID_SUBCATEGORIA SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
    ID_CATEGORIA INT,
	
    FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE TB_ROL (
    ID_ROL SERIAL PRIMARY KEY,
    DESCRIPCION CHAR(20) NOT NULL
);

CREATE TABLE TB_CARGO(
	ID_CARGO SERIAL PRIMARY KEY,
	DESCRIPCION CHAR(20) NOT NULL 
);

CREATE TABLE TB_USUARIO (
    ID_USUARIO SERIAL PRIMARY KEY,
    NOMBRES VARCHAR(50) NOT NULL,
    APE_MATERNO VARCHAR(50) NOT NULL,
    APE_PATERNO VARCHAR(50) NOT NULL,
    CORREO VARCHAR(50) UNIQUE NOT NULL,
    CLAVE VARCHAR(100) NOT NULL,
	TIPO_DOC CHAR(3) NOT NULL 
	CHECK(TIPO_DOC IN('DNI','PAS','CDX','CMP')),
	--DNI, PASAPORTE, CARNET DE EXTRANJERIA, CARNET MILITAR/POLICIAL
    NRO_DOC VARCHAR(15) UNIQUE NOT NULL,
    DIRECCION VARCHAR(70),
    ID_DISTRITO INT NOT NULL,
    TELEFONO CHAR(9) NOT NULL,
    ID_ROL INT DEFAULT 2,
	ID_CARGO INT,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	IMAGEN VARCHAR(150) DEFAULT NULL,
	PUBLIC_ID VARCHAR(100) DEFAULT NULL,
    ESTADO BOOLEAN DEFAULT TRUE,
    FCM_TOKEN VARCHAR(500) NULL,
    FCM_TOKEN_FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_DISTRITO) REFERENCES TB_DISTRITO(ID_DISTRITO),
    FOREIGN KEY (ID_ROL) REFERENCES TB_ROL(ID_ROL),
	FOREIGN KEY (ID_CARGO) REFERENCES TB_CARGO(ID_CARGO)
);

CREATE TABLE TB_EMPRESA(
	ID_EMPRESA SERIAL PRIMARY KEY,
    RUC CHAR(11) NOT NULL UNIQUE,
    RAZON_SOCIAL VARCHAR(100) NOT NULL,
	IMAGEN VARCHAR(150) DEFAULT NULL,
	PUBLIC_ID VARCHAR(100) DEFAULT NULL,
    TELEFONO CHAR(15) NOT NULL,
    DIRECCION VARCHAR(80) NOT NULL,
    ID_DISTRITO INT NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO BOOLEAN DEFAULT TRUE,
	
    FOREIGN KEY (ID_DISTRITO) REFERENCES TB_DISTRITO(ID_DISTRITO)
);

CREATE TABLE TB_SUCURSAL(
    ID_SUCURSAL SERIAL PRIMARY KEY,
	NOMBRE_UBICACION VARCHAR(50) NOT NULL, --PRIMAVERA/DASO/MIRAFLORES/ETC
	ID_EMPRESA INT,
	IMAGEN VARCHAR(150),
	PUBLIC_ID VARCHAR(100) DEFAULT NULL,
	ID_DISTRITO INT,
	DIRECCION VARCHAR(80) NOT NULL,
	FECHA_APERTURA DATE,

	FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA)
);

CREATE TABLE TB_PRODUCTO (
    ID_PRODUCTO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    ID_EMPRESA INT, -- A QUE TIENDA LE PERTENECE CADA PRODUCTO
    ID_SUBCATEGORIA INT,
    IMAGEN VARCHAR(150) DEFAULT NULL, 
	PUBLIC_ID VARCHAR(100) DEFAULT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO BOOLEAN DEFAULT TRUE,
	
    FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA),
    FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES TB_SUBCATEGORIA(ID_SUBCATEGORIA)
);

CREATE TABLE TB_PRODUCTO_SUCURSAL(
	ID_PRODUCTO_SUCURSAL SERIAL PRIMARY KEY,
	ID_PRODUCTO INT,
	ID_SUCURSAL INT,
	MIN_STOCK INT,
	STOCK INT DEFAULT 1,
	MAX_STOCK INT,
	PRECIO NUMERIC(10,2) NOT NULL,
	ESTADO BOOLEAN DEFAULT TRUE,

	FOREIGN KEY (ID_PRODUCTO) REFERENCES TB_PRODUCTO(ID_PRODUCTO),
    FOREIGN KEY (ID_SUCURSAL) REFERENCES TB_SUCURSAL(ID_SUCURSAL),
	UNIQUE (ID_PRODUCTO, ID_SUCURSAL)
);


CREATE TABLE TB_VENTA (
    ID_VENTA SERIAL PRIMARY KEY,
    ID_USUARIO INT,
	ID_SUCURSAL INT,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TOTAL NUMERIC(11,2),
    ESTADO CHAR(1) DEFAULT 'G', -- G,P,E,C
    TIPO_VENTA CHAR(1) DEFAULT 'R', -- R, P
    METODO_ENTREGA CHAR(1), -- S, D
	ESPECIFICACIONES TEXT,
    CONSTRAINT EST_CHECK CHECK (ESTADO IN ('G','P','E','C')),
    CONSTRAINT TIPO_VENTA_CHECK CHECK (TIPO_VENTA IN ('P','R')),
    CONSTRAINT MET_ENTREGA_CHECK CHECK (METODO_ENTREGA IN ('D','S') OR METODO_ENTREGA IS NULL),

	FOREIGN KEY (ID_SUCURSAL) REFERENCES TB_SUCURSAL(ID_SUCURSAL),
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
);

CREATE TABLE TB_DETALLE_VENTA (
    ID_DETALLE_VENTA SERIAL PRIMARY KEY,
    ID_VENTA INT NOT NULL,
    ID_PRODUCTO_SUCURSAL INT NOT NULL,
    CANTIDAD SMALLINT NOT NULL,
	PRECIO_UNITARIO NUMERIC(10,2), --ESTE PRECIO SERA PARA GUARDAR LOS PRECIOS QUE SE COMPRARON EN ESE MOMENTO
    SUB_TOTAL NUMERIC(10,2) NOT NULL,
    FOREIGN KEY (ID_VENTA) REFERENCES TB_VENTA(ID_VENTA),
    FOREIGN KEY (ID_PRODUCTO_SUCURSAL) REFERENCES TB_PRODUCTO_SUCURSAL(ID_PRODUCTO_SUCURSAL)
);


CREATE TABLE TB_PEDIDO (
    ID_PEDIDO SERIAL PRIMARY KEY,
    ID_VENTA INT NOT NULL UNIQUE,
	ID_SUCURSAL INT,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DIRECCION_ENTREGA VARCHAR(255) NOT NULL,
    LATITUD NUMERIC(10,6) NOT NULL,
    LONGITUD NUMERIC(10,6) NOT NULL,
    NUMERO_PEDIDO VARCHAR(50) NOT NULL UNIQUE,
    QR_VERIFICATION_CODE VARCHAR(150) NOT NULL UNIQUE,
    ID_REPARTIDOR INT,
    MOVILIDAD CHAR(1) NOT NULL,
    FECHA_ASIGNACION TIMESTAMP,            -- momento en el q se setea el estado a AS
    FECHA_EN_CAMINO TIMESTAMP,             -- momento en el q se setea el estado a EC
    FECHA_ENTREGA TIMESTAMP,               -- momento en el q se setea el estado a EN
    TIEMPO_ENTREGA_MINUTOS SMALLINT,       -- métrica de negocio (dif d minutos entre EN y EC)
    ESTADO VARCHAR(2) DEFAULT 'PE',
    OBSERVACIONES TEXT,

	FOREIGN KEY (ID_SUCURSAL) REFERENCES TB_SUCURSAL(ID_SUCURSAL),
    FOREIGN KEY (ID_VENTA) REFERENCES TB_VENTA(ID_VENTA),
    FOREIGN KEY (ID_REPARTIDOR) REFERENCES TB_USUARIO(ID_USUARIO),
    CONSTRAINT CHK_ESTADO_PEDIDO CHECK (ESTADO IN ('PE','AS','EC','CR','EN','FA')),
    CONSTRAINT CHK_MOVILIDAD CHECK (MOVILIDAD IN ('M', 'A'))
	--leyenda de estados
	--PE -> PENDIENTE
	--AS -> ASIGNADO(aceptado) 
	--EC -> EN CAMINO
	--CR -> CERCA
	--EN -> ENTREGADO
	--FA -> FALLIDO
);

CREATE TABLE TB_NOTIFICACIONES (
    ID_NOTIFICACION SERIAL PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    ID_PEDIDO INT NOT NULL,
	TIPO VARCHAR(50) NOT NULL,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LEIDA BOOLEAN DEFAULT FALSE,
    DESCARTADA BOOLEAN DEFAULT FALSE,         -- Indica si el usuario la eliminó de su listado

    FOREIGN KEY (ID_CLIENTE) REFERENCES TB_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES TB_PEDIDO(ID_PEDIDO),

	CONSTRAINT CHK_TIPO_NOTIFICACION CHECK (TIPO IN (
        'PEDIDO_PENDIENTE',
        'PEDIDO_ACEPTADO',
        'PEDIDO_EN_CAMINO',
        'PEDIDO_CERCA',
        'PEDIDO_ENTREGADO',
        'PEDIDO_FALLIDO'
    ))
);

CREATE INDEX IDX_NOTI_CLIENTE ON TB_NOTIFICACIONES (ID_CLIENTE);
-- Buscar notificaciones de un cliente que NO han sido descartadas.
CREATE INDEX IDX_NOTI_CLIENTE_DESCARTADA ON TB_NOTIFICACIONES (ID_CLIENTE, DESCARTADA);
-- notificaciones no leídas por cliente.
CREATE INDEX IDX_NOTI_CLIENTE_LEIDA ON TB_NOTIFICACIONES (ID_CLIENTE, LEIDA);

CREATE INDEX IDX_PEDIDO_REPARTIDOR ON TB_PEDIDO(ID_REPARTIDOR);
CREATE INDEX IDX_PEDIDO_ESTADO ON TB_PEDIDO(ESTADO);
CREATE INDEX IDX_PRODUCTO_SUCURSAL ON TB_PRODUCTO_SUCURSAL(ID_SUCURSAL);
